require: rubocop-rails

AllCops:
  Exclude:
    # bundled gems
    - db/schema.rb
    - vendor/**/*
    # package testing gems
    - test/vendor/**/*

Rails/Output:
  Exclude:
    - 'config/*.rb'
    - 'db/seeds.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/mailers/newsletter_mailer.rb'

Security/Eval:
  Exclude:
    - 'app/controllers/global_controller.rb'

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Next:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'test/test_helper.rb'

Lint/ImplicitStringConcatenation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/BlockLength:
  Max: 200
  Exclude:
    - 'test/**/*.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/routes.rb'

Metrics/ParameterLists:
  Exclude:
    - 'test/**/*.rb'

Metrics/ClassLength:
  Max: 1000
  Exclude:
    - 'test/**/*.rb'

Lint/SuppressedException:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*.rb'
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/deployer.rb'
    - 'lib/cloud_provider/internal.rb'
    - 'lib/cloud_provider/kubernetes.rb'
    - 'db/migrate/*.rb'

Style/ClassVars:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/base.rb'
    - 'db/migrate/*.rb'

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/base.rb'
    - 'db/migrate/*.rb'

Naming/MethodParameterName:
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor

Layout/EndAlignment:
  Enabled: false

Rails/Validation:
  Enabled: false