require: rubocop-rails

AllCops:
  Exclude:
    # bundled gems
    - vendor/**/*
    # package testing gems
    - test/vendor/**/*

#AllCops:
#  Exclude:
#    - 'path/to/excluded/file.rb'

Metrics/LineLength:
  Max: 100

Lint/ImplicitStringConcatenation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'test/**/*.rb'

Lint/HandleExceptions:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*.rb'
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/deployer.rb'
    - 'lib/cloud_provider/vultr.rb'

Style/ClassVars:
  Exclude:
    - 'lib/remote/ssh.rb'
    - 'lib/remote/sftp.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/docker_compose.rb' # to refactor
    - 'lib/deployment_method/deployer.rb'
    - 'lib/deployment_method/base.rb'
    - 'lib/cloud_provider/vultr.rb'

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/base.rb'
    - 'lib/cloud_provider/vultr.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/base.rb'
    - 'lib/cloud_provider/vultr.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor

Layout/EndAlignment:
  Enabled: false