require: rubocop-rails

AllCops:
  Exclude:
    # bundled gems
    - db/schema.rb
    - vendor/**/*
    # package testing gems
    - test/vendor/**/*

Rails/Output:
  Exclude:
    - 'config/*.rb'

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Lint/ImplicitStringConcatenation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 500
  Exclude:
    - 'test/**/*.rb'

Lint/HandleExceptions:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*.rb'
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/deployer.rb'
    - 'lib/cloud_provider/vultr.rb'
    - 'lib/cloud_provider/internal.rb'
    - 'db/migrate/*.rb'

Style/ClassVars:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/LeadingBlankLines:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/docker_compose.rb' # to refactor
    - 'lib/deployment_method/deployer.rb'
    - 'lib/deployment_method/base.rb'
    - 'lib/cloud_provider/vultr.rb'
    - 'db/migrate/*.rb'
    - 'app/models/website.rb'

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/base.rb'
    - 'lib/cloud_provider/vultr.rb'
    - 'db/migrate/*.rb'

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor
    - 'lib/deployment_method/base.rb'
    - 'lib/cloud_provider/vultr.rb'
    - 'db/migrate/*.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'lib/io/dir.rb' # to refactor
    - 'lib/deployment_method/runner.rb' # to refactor

Layout/EndAlignment:
  Enabled: false