notifications:
  slack: openodeio:6BDG0odfHQqNmWXoYcDfpV2y

language: ruby

before_script:
- sudo apt-get install -qq sshpass
- nvm install 10
- nvm alias default 10
- node -v
- npm i -g openode

script:
  - bundle exec rubocop
  - bundle exec bin/rails test

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE openode_test;'

deploy:
  provider: script
  script: env bash scripts/deploy.sh
  on:
    branch: master