language: ruby

script:
  - bundle exec rubocop
  - bundle exec bin/rails test

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE openode_test;'

deploy:
  provider: script
  script: env bash scripts/deploy.sh
  on:
    branch: master