application:
  base_hostname: openode.io
  hostname_private_cloud: openode.dev
  dns:
    type: vultr
    api_key: xxxxx
  docker:
    build_servers:
      - ip: 127.0.0.1
        user: root
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          AAA
          BBB
          CCC
          -----END RSA PRIVATE KEY-----
        root_files_path: /home/
    images_location:
      docker_server: https://index.docker.io/v1/
      docker_username: test
      repository_name: openode_prod
      docker_password: t123456
      docker_email: test@openode.io
  clouds:
    - type: internal
      locations:
        - str_id: canada2
          full_name: Montreal (Canada2)
          country_fullname: Canada2
          servers:
            - ip: 127.0.0.100
              user: root
              password: hellorroot
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
            - ip: 127.0.0.101
              user: root
              private_key: |
                -----BEGIN RSA PRIVATE KEY-----
                AAA
                BBB
                CCC
                -----END RSA PRIVATE KEY-----
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
    - type: dummy
    - type: vultr
      api_key: xxxxx