application:
  base_hostname: openode.io
  hostname_private_cloud: openode.dev
  addons:
    repository_url: https://github.com/openode-io/addons/
    repository_fileroot_url: https://raw.githubusercontent.com/openode-io/addons/master/
    repository_tree_url: https://api.github.com/repos/openode-io/addons/git/trees/master?recursive=true
  pricing:
    typical_server_cost: 80
    typical_allocatable_ram: 9600
    price_multiplier: 1.8
    blue_green_ratio_plan_cost: 0.2
  docker:
    build_servers:
      - ip: 127.0.0.1
        user: root
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          AAA
          BBB
          CCC
          -----END RSA PRIVATE KEY-----
        root_files_path: /home/
    images_location:
      registry_impl_type: digital_ocean
      docker_server: docker.io
      docker_username: test
      repository_name: openode_prod
      docker_password: t123456
      docker_email: test@openode.io
  clouds:
    - type: internal
      cloud_type: cloud
      locations:
        - str_id: canada2
          provider_id: can2
          full_name: Montreal (Canada2)
          country_fullname: Canada2
          servers:
            - ip: 127.0.0.100
              user: root
              password: hellorroot
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
            - ip: 127.0.0.101
              user: root
              private_key: |
                -----BEGIN RSA PRIVATE KEY-----
                AAA
                BBB
                CCC
                -----END RSA PRIVATE KEY-----
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
          location_subdomain: ""
          base_hostname: openode.io
        - str_id: canada
          provider_id: mycan
          full_name: Montreal (Canada)
          country_fullname: Canada
          servers:
            - ip: 127.0.0.100
              user: root
              password: hellorroot
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
            - ip: 127.0.0.101
              user: root
              private_key: |
                -----BEGIN RSA PRIVATE KEY-----
                AAA
                BBB
                CCC
                -----END RSA PRIVATE KEY-----
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
          location_subdomain: ""
          base_hostname: openode.io
    - type: kubernetes
      storage_class_name: do-block-storage
      limit_memory_for_rolling_update_strategy: 0 # if >=, will use Recreate strategy
      locations:
        - str_id: canada
          provider_id: kubecan
          full_name: Montreal (Canada2)
          country_fullname: Canada2
          builder_kubeconfig_path: /var/www/openode-api/config/kubernetes/production-canada2.yml
          cname: canada.openode.io
          external_addr: 127.0.0.1
          location_subdomain: ""
          base_hostname: openode.io
        - str_id: usa
          full_name: New York (USA)
          country_fullname: United States
          cname: usa.openode.io
          builder_kubeconfig_path: /var/www/openode-api/config/kubernetes/production-usa.yml
          external_addr: 127.0.0.2
          location_subdomain: ""
          base_hostname: openode.io
        - str_id: eu
          full_name: Paris (France)
          country_fullname: France
          cname: eu.openode.io
          builder_kubeconfig_path: /var/www/openode-api/config/kubernetes/production-eu.yml
          external_addr: 127.0.0.2
          location_subdomain: "eu"
          base_hostname: openode.io
    - type: gcloud_run
      cloud_type: gcloud
      locations:
        - str_id: us-central-1
          provider_id: us-central1
          full_name: Iowa (USA)
          country_fullname: USA
          cname: us_central_1.openode.io
          external_addr: 127.0.0.2
          location_subdomain: us
          base_hostname: openode.dev
          builder_kubeconfig_path: /home/user/works/openode-api/config/kubernetes/development-us-central-1.yml
          load_balancer_ip: 34.69.135.171
        - str_id: eu-west-1
          provider_id: europe-west1
          full_name: Belgium (Europe)
          country_fullname: Belgium
          cname: eu_west_1.openode.io
          external_addr: 127.0.0.2
          location_subdomain: eu
          base_hostname: openode.dev
          builder_kubeconfig_path: /home/user/works/openode-api/config/kubernetes/development-us-central-1.yml
          load_balancer_ip: 34.69.135.171
        - str_id: canada
          provider_id: can
          full_name: Can (Can)
          country_fullname: Canada
          cname: ca.openode.io
          external_addr: 127.0.0.2
          location_subdomain: ""
          base_hostname: openode.io
          builder_kubeconfig_path: /home/user/works/openode-api/config/kubernetes/development-us-central-1.yml
          load_balancer_ip: 34.69.135.171
    - type: dummy
