application:
  base_hostname: openode.io
  hostname_private_cloud: openode.dev
  pricing:
    typical_server_cost: 80
    typical_allocatable_ram: 9600
    price_multiplier: 1.2
    blue_green_ratio_plan_cost: 0.2
  docker:
    build_servers:
      - ip: 127.0.0.1
        user: root
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          AAA
          BBB
          CCC
          -----END RSA PRIVATE KEY-----
        root_files_path: /home/
    images_location:
      registry_impl_type: digital_ocean
      docker_server: docker.io
      docker_username: test
      repository_name: openode_prod
      docker_password: t123456
      docker_email: test@openode.io
  clouds:
    - type: internal
      locations:
        - str_id: canada2
          full_name: Montreal (Canada2)
          country_fullname: Canada2
          servers:
            - ip: 127.0.0.100
              user: root
              password: hellorroot
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
            - ip: 127.0.0.101
              user: root
              private_key: |
                -----BEGIN RSA PRIVATE KEY-----
                AAA
                BBB
                CCC
                -----END RSA PRIVATE KEY-----
              ram_mb: 5000
              cpus: 2
              disk_gb: 200
    - type: kubernetes
      storage_class_name: do-block-storage
      limit_memory_for_rolling_update_strategy: 0 # if >=, will use Recreate strategy
      locations:
        - str_id: canada
          full_name: Montreal (Canada2)
          country_fullname: Canada2
          builder_kubeconfig_path: /var/www/openode-api/config/kubernetes/production-canada2.yml
          cname: canada.openode.io
          external_addr: 127.0.0.1
        - str_id: usa
          full_name: New York (USA)
          country_fullname: United States
          cname: usa.openode.io
          builder_kubeconfig_path: /var/www/openode-api/config/kubernetes/production-usa.yml
          external_addr: 127.0.0.2
    - type: dummy