---
:max_retries: 1
:retry: 1
:concurrency: <%= Deployment::MAX_CONCURRENCY %>
test:
  :concurrency: 1
development:
  :concurrency: 5
production:
  :concurrency: <%= Deployment::MAX_CONCURRENCY %>
:queues:
  - critical
  - default
  - low